model:
  type: subgraph_diffusion 
  network: dualenc
  hidden_dim: 128
  num_convs: 6
  num_convs_local: 4
  cutoff: 10.0
  mlp_act: relu
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 5.e-2 
  num_diffusion_timesteps: 200
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false 
  same_mask_steps: 10
  mask_pred: MLP #

train:
  seed: 2021
  batch_size: 64
  val_freq: 2000
  max_iters: 2000000
  max_grad_norm: 10000.00
  anneal_power: 2.0
  optimizer:
    type: adam
    lr: 1.e-3
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 30

dataset:
  train: ./data/GEOM/QM9/train_data_40k_subgraph.pkl
  val: ./data/GEOM/QM9/val_data_5k_subgraph.pkl
  test: ./data/GEOM/QM9/test_data_1k.pkl
